### ISSUE TITLE
Edit/Trash Icons

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#116]
![Edit:Trash Icons](https://user-images.githubusercontent.com/48923883/56234838-ff5a7a00-603a-11e9-9f22-8d7791c330fe.png)

The icons are not entirely clickable. A user has to scan over the small icon before the cursor changes to a hand and the icon becomes clickable. Can we make the entire icon clickable? It is frustrating to use currently

**Comment by akhilesh-94** [comment]
@JRWinWin Could you check now again, made some changes

**Comment by BethRR** [comment]
@akhilesh-94 I think the issue is not yet resolved. Attached is screenshot of the issue and shows that the cursor doesn't change even when pointer tip is centered on the icon. Tested in Chrome/Windows 10
![2019-04-30_SelectionIssue](https://user-images.githubusercontent.com/49886260/56999063-8e4eb280-6b62-11e9-870b-436d63421f92.png)

**Comment by akhilesh-94** [comment]
> @akhilesh-94 I think the issue still present in NOTES. Attached is screenshot of the issue and shows that the cursor doesn't change even when pointer tip is centered on the icon. Tested in Chrome/Windows 10
> ![2019-04-30_SelectionIssue](https://user-images.githubusercontent.com/49886260/56999063-8e4eb280-6b62-11e9-870b-436d63421f92.png)

Made the required changes

**Comment by BethRR** [comment]
confirmed fixed.
