### ISSUE TITLE
Org Chart - Child Organization Save Redirect

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#120]
![Org Chart - Child Organization Save Redirect](https://user-images.githubusercontent.com/48923883/56235788-f5397b00-603c-11e9-83a6-cd6d5d48e50b.png)

**Comment by BethRR** [comment]
For MVP: Clicking on Save should take the user to the org chart with the newly created child org and parents visible/centered in screen.

Longer Term: We'd like to see a list of the children in this screen so that a user can add multiple children while they are here. Also would like to add functionality to support adding org structure/hierarchy  in a structured list view rather than a diagram view. More details to come from Beth.

**Comment by sunnytambi** [comment]
@BethRR , we can take user to the landing page of newly created child org rather than the org chart.
The reason is playing with visibility/centering of the new child is going to be very time consuming and error prone.

**Comment by BethRR** [comment]
Closing as resolved. The current implementation collapses the tree to the highest level available. This is fine for MVP.
