### ISSUE TITLE
Uploading file fails and does not send slack notification or write to logs visible in Kibana

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#683]
Issue: I have attempted to upload this file multiple times and it has never worked. After uploading, I navigate back to the Organization Management page and get the blue "Upload in Progress, a notification will be in Slack" message banner. However, the upload never processes AND nothing gets posted in slack. The upload is a failure but the UI seems to be telling the user that there are no issues.

There are two issues in this card:

1)  Why did this file fail the upload process? It conforms to the upload requirements.

2) Users should see an error message with the upload has failed rather than a message implying that all is well. Users must have an accurate representation of the processes happening beneath the UI for Bulk Upload

attached as a .tx because github doesn't support .csv
[Bulk_Upload_TEST_IRS_WA_BETH_TEST.txt](https://github.com/winwinwiki/winwin-frontend/files/3699677/Bulk_Upload_TEST_IRS_WA_BETH_TEST.txt)

**Comment by BethRR** [comment]
@sunnytambi @Arvind this is related to bug #696

**Comment by arvindkhatik012** [comment]
@BethRR we tried to upload the bulk upload file and it worked fine and as I told you in my earlier comments that whenever a org will fail to upload its error details will be there in the status file under comments.

![image](https://user-images.githubusercontent.com/45760420/68366541-9ca50900-0159-11ea-9136-5dde10d5e3a8.png)

https://winwin2016.slack.com/archives/CL45P64BA/p1573108627000600

**Comment by arvindkhatik012** [comment]
@BethRR We checked the issue and found that the error occured due to use of incorrect template .
You have used fields SDG Tags , SPI tags instead of spiTagIds and sdgTagIds and because of that system was not able to recognize the correct fields mapping.

Note: Please download the template first and than try to upload again or update your template with correct field name.
[admin_bulk_create_template .csv.txt](https://github.com/winwinwiki/winwin-frontend/files/3824124/admin_bulk_create_template.csv.txt)

![image](https://user-images.githubusercontent.com/45760420/68469499-4e1e6a00-0240-11ea-878f-d067b4f03dfa.png)

**Comment by BethRR** [comment]
The reason this was left open was that the upload failed and did not send failure notification or reason for failure.

**Comment by BethRR** [comment]
Per discussion with @sunnytambi -- Talentica will look into why multiple error messages/warnings appear in the client and resolve. Currently 2-3 messages pop up making it difficult to read the error and understand the issue.

**Comment by sunnytambi** [comment]
1. Fixed the multiple notification issue on UI
2. All upload failures and respective statuses (start, end, fail, pass, etc.) are also available in Slack.
