### ISSUE TITLE
Bulk Upload treats an empty field as a valid " " text entry rather than un-permitted null

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#720]
Situation: I uploaded a file via Bulk Upload which contained 69k valid lines of data and there was 600k lines with sporadic NTEE code data only, invalid data.
The name field is a required field, but in this instance, it was empty. The bulk upload process continued and many entries were uploaded with empty name fields. 

Expected result: The expected result would be an error message and a stopped bulk upload process.
In order for this bulk upload to have worked, the upload process must interpret empty fields as blank text entries. This must be fixed to prevent empty name fields from being uploaded again.

**Comment by arvindkhatik012** [comment]
we have fixed the issue

**Comment by BethRR** [comment]
Hi @Arvind -- Since not all organizations will have datasets, resources or programs, **we shouldn't require names for anything other than organization.** If any field other than organization name is empty when bulk uploading or migrating, it should be treated as null rather than an empty string (which I think is what the logic does anyway, is that right)?

**Comment by arvindkhatik012** [comment]
@BethRR As I explained we have only added db level not null constraints on the below fields and we have added require inline validation on UI for organization name and program name while creation from UI.
name      -  organization
name      -  program
category -  dataset_category
category - resource_category
